Reddit/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :links
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "links#index"
end

Reddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Reddit/app/models/link.rb
class Link < ApplicationRecord
    belongs_to :user
end

Reddit/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
end

Reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Reddit/app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

Reddit/app/helpers/application_helper.rb
module ApplicationHelper
end

Reddit/app/helpers/links_helper.rb
module LinksHelper
end

Reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  <header class='navbar navbar-default' role='navigation'>
  <div class='navbar-inner'>
    <div class='container'>
      <div id='logo' class='navbar-brand'><%= link_to "Reddit", root_path %></div>
      <nav class='collapse navbar-collapse navbar-exl-collapse'>
        <% if user_signed_in? %>
        <ul class='nav navbar-nav navbar-right'>
          <li><%= link_to 'Submit', new_link_path %></li>
          <li><%= link_to 'Account', edit_user_registration_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete%></li>
        </ul>
            <% else%>
        <ul class='nav navbar-nav pull-right'>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
        </ul>
         <% end %>
      </nav>
    </div>
  </div>
</header>

    <div id='main' class='container'>
        <% flash.each do |name, msg|%>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
        <% end%>

      <div id='container' class='col-md-9 center-block'>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

Reddit/app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :link_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, id: :link_url, class:'form-control' %>
  </div>
  <br>
  <div class="form-group">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

Reddit/app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

Reddit/app/views/links/index.html.erb
<% @links.each do |link| %>
<div class='link row clearfix'>
<h3><%= link_to link.title, link%>
<br>
<small class='author'>Submmited <%=time_ago_in_words(link.created_at)%> by <%= link.user.email%></small>
</h3>
</div>
<% end %>

Reddit/app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path, class:'btn btn-default' %>

Reddit/app/views/links/show.html.erb
<div class='page-header'>
  <h2><%= @link.title %></h2>
  <small>by <%= @link.user.email%></small>
</div>
<div class='btn-group'>
 <%= link_to 'View URL', @link.url, class: 'btn btn-primary' %>
  <%= link_to 'Edit', edit_link_path(@link), class: 'btn btn-default' %>
  <%= link_to 'Back', links_path, class: 'btn btn-default' %>
</div>